### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by iago-lito** [rascal222/TER-Warbot-2016#14]
Because of #10 and #13, I need to put all my classes into a single file, which is a pain.

`config.yml`:

    AgentsBrainClasses:
        WarExplorer: callbacks.py
        WarBase: callbacks.py
        WarTurret: callbacks.py
        .. etc.

Now that `callbacks.py` is more that 1000 lines long, my agents freeze with this java exception:

    java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!

What a shame! I finally managed to perform my imports by adding my python modules to the .jar with:

    jar uf warbot.jar AbstractAgent.py

after which the following:

    from AbstractAgent import *

.. finally works in python if I use this modified `warbot.jar`.

Anyway, I wish I wouldn't need to do this, and that this will be considered as a legal move on Wednesday.

**Comment by ghost** [comment]
> I wish that this will be considered as a legal move on Wednesday.

I don't think so because you're modifying the content of the warbot archive.

But I agree, importing local Python modules should be the next feature to support. I don't know if there's a reason to it, but the current state of the Python API just forbids the creation of reusable code.

**Comment by iago-lito** [comment]
Well. I can't compete then.

> You're modifying the content of the warbot archive.

I am not. I am adding content to the warbot archive (my team code), because warbot cannot access it otherwise. I'll let you do it yourself if you prefer, which I would understand.

**Comment by ghost** [comment]
Ok, I finally managed to import custom modules. It is just dealing with Python import paths.

I assume your team folder is called `fooTeam`.

- Create another folder named `fooTeam` in `<warbotFolder>/Lib`. Move your shared files to it.

- Create a `__init__.py` file within. In this init file, import your symbols.
For example, if you have a file named `constants.py`, you can write `import constants`.

- In the beginning of your agent files, add :

```
import fooTeam

# Do your stuff, e.g :
print(fooTeam.constants.foo)
```

Anyway, it's a bit too late, but I think it will be a legal move tomorrow.

**Comment by iago-lito** [comment]
Yo! This works fine, I don't need to augment the `.jar` anymore and I can use the original one. Cheers :)

**Comment by stardisblue** [comment]
Just hoping it will be a legal move and stable tomorrow ...

**Comment by iago-lito** [comment]
Come on, it is just a matter of adding a link to warbot folder ;) Consider this:

`generate.bash` (in your team folder):

    #!/bin/bash -e

    # Link the module from warbot library folder so that python import works

    warbotFolder=$1
    module=$2 # relative to pwd
    action=$3
    if [[ -z $action ]]; then
        action=install
    fi
    libFolder=$warbotFolder/Lib # warbot Lib folder, in python search path
    linkPath=$libFolder/$module

    case $action in
        install)
            echo "Linking to $libFolder"
            # Create the lib folder if it does not exist
            mkdir -p $libFolder

            # just link our module to it
            ln -s $(pwd)/$module $linkPath
            ;;
        uninstall)
            # remove the link
            echo "Removing $linkPath"
            rm -f $linkPath
            # NOT the folder even if empty now. That ain't no nice u_u
            ;;
        *)
            echo "unknown action: $action"
            exit 1
            ;;
    esac
    echo "done."

    exit

Then just use (in my case):

    ./generate.bash /opt/warbot myteam

then launch warbot, play.. then:

    ./generate.bash /opt/warbot myteam uninstall

to clean before you go. that's it ;)

**Comment by stardisblue** [comment]
wow, neat 👍 !

**Comment by ghost** [comment]
I'm sure it will be legal.

Warbot searches automatically for files in the `Lib` folder. It just wasn't mentioned by the documentation.

**Comment by stardisblue** [comment]
hahaha, after trying i have this :

```py
Traceback (most recent call last):
  File "<string>", line 8, in action
  File "<string>", line 36, in actionWarBase
  File "<string>", line 81, in recievingMessages
AttributeError: 'module' object has no attribute 'getCarthesianAgentFromMessage'
```

and i have imported it correctly :

```py
from teamname import Class
```

i give up --'

**edit : nevermind the solution was**

```py
from teamname.Class import Class 
```

**Comment by ghost** [comment]
Yeah, Python differentiates modules (files) from symbols (classes, functions, etc).
