### ISSUE TITLE
WarEngineers cannot create?

### ISSUE THREAD

**Issue by iago-lito** [rascal222/TER-Warbot-2016#15]
Calling `create()` from `actionWarEngineer()` raises:

      File "<string>", line 44, in create
      File "<string>", line 711, in create
    AttributeError: 'WarEngineer' object has no attribute 'create'

Are engineers *really* able to create Turrets in python? õ.Ô

**Comment by iago-lito** [comment]
Using `setNextBuildingToCreate(WarAgentType.WarTurret)` then `build()` does nothing -_-
I am leaving this feature.

**Comment by ghost** [comment]
You must `return build()`, not just call the function.

It is the same behavior as `return move()/idle()/eat()...`.

**Comment by iago-lito** [comment]
I do `return build()`. Would it have to see with the fact that a Turret costs `1500` and an Engineer only has `1500` as max heath in the settings?

**Comment by iago-lito** [comment]
Confirmed. Setting `WarEngineer: MaxHealth: 1520` in `warbot_settings.yml` enables the construction. So the latests warbot settings do not allow Turrets building. What do we do?

**Comment by iago-lito** [comment]
Solved with one of [theses releases](http://www.lirmm.fr/~ferber/ProgAgent/index.html).
