### ISSUE TITLE
Get execution errors content frow within Warbot

### ISSUE THREAD

**Issue by iago-lito** [rascal222/TER-Warbot-2016#7]
If I ask my base to do the following in python:

    def actionWarBase():
        dummy = 'a' + 5

then I get an error during the simulation. But my base only shows

    Erreur à l'interprétation

and not 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<string>", line 2, in actionWarBase
    TypeError: Can't convert 'int' object to str implicitly

If we cannot access the errors thrown by python or java. Debugging will just be a nightmare.. and developping agents brains will take forever :(

**Comment by stardisblue** [comment]
you need to encaplusalte ints to strings : 

``` python
dummy = "a" + str(5)
```

**Comment by iago-lito** [comment]
Haha, of course. Sorry for having not been clear. This is not my point: the issue is that there is no way I can access the error message nor the traceback from warbot. Writing:

```
def actionWarBase():
    raise TypeError("an error occured in my brain")
```

will get me:

```
Erreur à l'interprétation
```

and not:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in actionWarBase
TypeError: an error occured in my brain
```

.. which makes debugging very difficult if our code is very long.

So this is the feature request: is there a way we could get execution error messages from within warbot ?

**Comment by stardisblue** [comment]
when you execute the jar package in the console with : `java -jar ....` it will output the errors 😉

**Comment by iago-lito** [comment]
Yeah! I hadn't noticed. That's cool at least, thanks :) I guess this makes this feature request less urgent to process.

**Comment by stardisblue** [comment]
I think you can close it, since "within warbot" is only useful if it has the "reload team script option" #6
